# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               cole lyman
tagline:             CS, Bioinformatics, Big Data, Python & Life
url:                 http://colelyman.com
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Cole Lyman
  url:               https://twitter.com/colelyman
  email:             cole@colelyman.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
